#include <map>
#include <vector>
#include <set>
#include <wx/wx.h>
#include <wx/treectrl.h>
#include <wx/button.h>
#include <wx/combobox.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>
#include <wx/aui/aui.h>
#include <wx/aui/framemanager.h>
#include <wx/xml/xml.h>
